# Generated by Django 5.0 on 2026-06-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0002_alter_chatsession_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text="Primary question (e.g. 'What is your refund policy?')", max_length=500)),
                ('answer_text', models.TextField(help_text='The exact response the bot should give.')),
                ('keywords', models.TextField(help_text="Comma-separated synonyms and aliases for fuzzy matching (e.g. 'refund, money back, guarantee, warranty')")),
                ('category', models.CharField(choices=[('faq', 'General FAQ'), ('service', 'Service Information'), ('troubleshooting', 'Troubleshooting Guide'), ('policy', 'Store Policy'), ('booking', 'Booking Process')], default='faq', max_length=20)),
            ],
            options={
                'verbose_name': 'Knowledge Base Article',
                'verbose_name_plural': 'Knowledge Base Articles',
            },
        ),
        migrations.CreateModel(
            name='KnownVisualIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(help_text="e.g. 'Swollen Capacitor', 'Burnt Trace'", max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('diagnosis_text', models.TextField(help_text='The predefined diagnosis to return without hitting Gemini.')),
            ],
            options={
                'verbose_name': 'Known Visual Issue',
                'verbose_name_plural': 'Known Visual Issues',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_estimate', models.CharField(blank=True, max_length=100)),
                ('tags', models.TextField(help_text="Comma-separated tags for rule-based matching (e.g. 'cheap, beginner, starter, low budget')")),
            ],
            options={
                'verbose_name': 'Product / Recommendation',
                'verbose_name_plural': 'Products / Recommendations',
            },
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service Request / Booking', 'verbose_name_plural': 'Service Requests / Bookings'},
        ),
        migrations.AddField(
            model_name='message',
            name='generated_by',
            field=models.CharField(choices=[('user', 'User Input'), ('layer1_heuristic', 'L1: Hardcoded/Heuristic'), ('layer2_kb', 'L2: Knowledge Base NLP'), ('layer3_gemini', 'L3: Gemini AI Emergency')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='desired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='desired_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
