# Generated by Django 5.0 on 2026-06-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0003_knowledgebasearticle_knownvisualissue_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='current_intent',
            field=models.CharField(blank=True, help_text='Tracks active conversation flow', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='intent_step',
            field=models.IntegerField(default=0, help_text='Tracks step index within the active intent'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='state_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores variables collected during flow'),
        ),
    ]
