# Generated by Django 5.0 on 2026-06-16 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0004_chatsession_current_intent_chatsession_intent_step_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service Request', 'verbose_name_plural': 'Service Requests'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_estimate',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='desired_date',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='desired_time',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(help_text="e.g. 'AV Receiver', 'Tower Speaker', 'Integrated Amp'", max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.TextField(help_text="Comma-separated tags for matching (e.g. 'cheap, beginner, starter, small room')"),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'Evaluating'), ('completed', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_type', models.CharField(help_text="e.g. 'Site Visit', 'Home Theatre Calibration', 'PCB Repair Drop-off'", max_length=150)),
                ('desired_date', models.DateField(blank=True, null=True)),
                ('desired_time', models.TimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='chatbot_api.chatsession')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_reasoning', models.TextField(help_text="Why did the AI recommend this? (e.g. 'Matches room size 15x20')")),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_in', to='chatbot_api.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='chatbot_api.chatsession')),
            ],
            options={
                'verbose_name': 'AI Recommendation',
                'verbose_name_plural': 'AI Recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
