# Generated by Django 5.0 on 2026-06-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0005_alter_product_options_alter_servicerequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='related_topics',
            field=models.TextField(blank=True, help_text='Comma-separated related article questions for internal linking.'),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='short_answer',
            field=models.TextField(blank=True, help_text='1-3 sentence concise answer for chatbot and WhatsApp.'),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='subcategory',
            field=models.CharField(blank=True, help_text="e.g. 'Protect Mode', 'HDMI ARC', 'Capacitor Ageing'", max_length=100),
        ),
        migrations.AddField(
            model_name='knowledgebasearticle',
            name='synonyms',
            field=models.TextField(blank=True, help_text='Comma-separated alternative phrasings of the question.'),
        ),
        migrations.AlterField(
            model_name='knowledgebasearticle',
            name='answer_text',
            field=models.TextField(help_text='Detailed engineering-level answer (100-250 words).'),
        ),
        migrations.AlterField(
            model_name='knowledgebasearticle',
            name='category',
            field=models.CharField(choices=[('faq', 'General FAQ'), ('home_theatre', 'Home Theatre'), ('dolby_atmos', 'Dolby Atmos'), ('amplifier_repair', 'Amplifier Repair'), ('pcb_repair', 'PCB Repair'), ('hdmi_repair', 'HDMI Board Repair'), ('dsp_channels', 'DSP & Lost Channels'), ('speaker_repair', 'Speaker Repair'), ('subwoofer', 'Subwoofers'), ('calibration', 'Calibration'), ('hifi_audio', 'Hi-Fi Audio'), ('commercial_audio', 'Commercial Audio'), ('preventive_maintenance', 'Preventive Maintenance'), ('service', 'Service Information'), ('troubleshooting', 'Troubleshooting Guide'), ('policy', 'Store Policy'), ('booking', 'Booking Process')], default='faq', max_length=30),
        ),
        migrations.AlterField(
            model_name='knowledgebasearticle',
            name='keywords',
            field=models.TextField(help_text='Comma-separated synonyms and aliases for fuzzy matching.'),
        ),
    ]
